spring.application.name=InventoryService
server.port=${APP_PORT}



#DATABASE CONFIGS
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# KAFKA CONFIG
spring.kafka.bootstrap-servers=${KAFKA_URL}

#TOPICS
CHECKED_INVENTORY=checked-inventoryItem
INVENTORY_REVERSE=inventoryItem-reverse
FAILED_CHECK_INVENTORY=failed-check-inventoryItem
CHECK_INVENTORY=check-inventoryItem

# --- PRODUCER CONFIG ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=\
  org.springframework.kafka.support.serializer.JsonDeserializer

# --- CONSUMER CONFIG ---
spring.kafka.consumer.group-id=inventoryItem-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=\
  StartCheckInventoryEvent:org.ecommerce.inventoryservice.dto.StartCheckInventoryEvent,\
  inventoryReverse:org.ecommerce.inventoryservice.dto.InventoryReverseEvent


spring.kafka.consumer.properties.spring.json.trusted.packages=org.eccommerce.cordinator.dto
spring.kafka.producer.properties.spring.json.type.mapping=\
  checkedInventory:org.ecommerce.inventoryservice.dto.CheckedInventoryEvent


spring.jackson.deserialization.fail-on-unknown-properties=false