server.port=8080

spring.application.name=api-gateway

#  Route for  "Order Service"
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/order/**

# Expose actuator and gateway routes for monitoring
management.endpoints.web.exposure.include=health,info,gateway
