spring.application.name=OrderService
server.port=${APP_PORT}
spring.jpa.hibernate.ddl-auto=update

# ---APIS ---
ORDER_API=/api/order
GET_ALL_ORDER=/get-all
ORDER_PLACE=/place-order
# -- TOPIC ---
ORDER_CREATED=order-created

# --- DB CONFIG ---
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.kafka.bootstrap-servers=${KAFKA_URL}


# --- PRODUCER CONFIG ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties.spring.json.type.mapping=\
  StartOrderPlacedEvent:org.eccommerce.orderservice.dto.StartOrderPlacedEvent

# --- CONSUMER CONFIG ---
spring.kafka.consumer.group-id=order-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=\
OrderCompletedEvent:org.eccommerce.orderservice.dto.OrderCompletedEvent,\
OrderCancelledEvent:org.eccommerce.orderservice.dto.OrderCancelledEvent
