input {
  beats {
    port => 5044
  }
}

filter {
  # This "dissect" block breaks your log line into separate fields
  dissect {
    mapping => {
      "message" => "%{ts} %{+ts} [%{thread}] %{level} %{logger} - %{log_msg}"
    }
  }

  # This converts the text "ts" into an actual clickable Date in Kibana
  date {
    match => [ "ts", "yyyy-MM-dd HH:mm:ss" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}