spring.application.name=CordinatorService
server.port=${APP_PORT}


# --- TOPICS ---
ORDER_CREATED=order-created
ORDER_CANCELLED=order-cancelled
ORDER_COMPLETED=order-completed

CHECK_INVENTORY=check-inventoryItem
CHECKED_INVENTORY=checked-inventoryItem
INVENTORY_REVERSE=inventoryItem-reverse
FAILED_CHECK_INVENTORY=failed-check-inventoryItem

START_PAYMENT=start-payment
FINISH_PAYMENT=finish-payment
FAIL_PAYMENT=fail-payment

#DATABASE CONFIGS
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# KAFKA CONFIG
spring.kafka.bootstrap-servers=${KAFKA_URL}


# --- PRODUCER CONFIG ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.spring.json.type.mapping=\
  StartCheckInventoryEvent:org.eccommerce.cordinator.dto.InventoryService.StartCheckInventoryEvent,\
  inventoryReverse:org.eccommerce.cordinator.dto.InventoryService.InventoryReverseEvent,\
  OrderCompletedEvent:org.eccommerce.cordinator.dto.OrderService.OrderCompletedEvent,\
  OrderCancelledEvent:org.eccommerce.cordinator.dto.OrderService.OrderCancelledEvent,\
  StartPaymentEvent:org.eccommerce.cordinator.dto.PaymentService.StartPaymentEvent





# --- CONSUMER CONFIG ---
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=\
org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=\
  checkedInventory:org.eccommerce.cordinator.dto.InventoryService.CheckedInventoryEvent,\
  StartOrderPlacedEvent:org.eccommerce.cordinator.dto.OrderService.StartOrderPlacedEvent,\
  finishedPaymentEvent:org.eccommerce.cordinator.dto.PaymentService.FinishedPaymentEvent,\
  failedPayment:org.eccommerce.cordinator.dto.PaymentService.PaymentFailedEvent



spring.kafka.consumer.properties.spring.json.trusted.packages=*


# Logging Configuration
# Set the default level to INFO or WARN (silences most library noise)
logging.level.root=INFO

logging.level.org.apache.kafka=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.kafka=ERROR

logging.level.org.eccommerce=TRACE

# Log file configuration
logging.file.name=logs/coordinator-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
